config/routes.rb
Rails.application.routes.draw do
  get 'messages/index' => 'messages#index'
  post 'confirm' => 'messages#confirm'
  post 'done' => 'messages#done'
  get 'posts/index'
  get '/' => "home#top"
  get 'sendgrid' => "home#sendgrid"
  get 'about' => "home#about"
  get 'photo' => "home#photo"
  get 'access' => "home#access"
  get 'price' => "home#price"
  get 'contact' => "home#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  attr_accessor :name, :email, :content

  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :content, presence: true, length: { maximum: 200 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def photo
  end

  def price
  end

  def access
  end

  def sendgrid
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @message = Message.new
  end

  def confirm
    @message = Message.new(message_params)
    if @message.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def done
    @message = Message.new(message_params)
    if params[:back]
      render :action => 'index'
    else
      MessageMailer.received_email(@message).deliver_now
      render :action => 'done'
    end
  end

  private
  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/access.html.erb
<div class="access-info">
  <div class="container">
    <h1>神奈川県横須賀市『追浜駅』から徒歩10分</h1>
    <div class="access-map">

      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3255.699874360735!2d139.6285232!3d35.3134382!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6018413dde4cee0b%3A0x32867daa145ada7a!2z44CSMjM3LTAwNjQg56We5aWI5bed55yM5qiq6aCI6LOA5biC6L-95rWc55S677yS5LiB55uu77yR77yS!5e0!3m2!1sja!2sjp!4v1622256952829!5m2!1sja!2sjp" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
  </div>
</div>

app/views/home/photo.html.erb
<div class="photos">
  <div class="container">
    <h2>順次掲載予定</h2>
  </div>
</div>

app/views/home/price.html.erb
<div class="price-list">
  <div class="container">
    <p>家賃(個室): 2万8000円/月</p>
    <p>共益費: 1万円/月</p>
  </div>
</div>

app/views/home/top.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Umiwataru</title>
  <link rel="stylesheet" href="stylesheet.css">
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
</head>
<body>
  <div class="top-wrapper">
    <div class="container">
      <div class="background-image">
      </div>
    </div>
  </div>
  <div class="middle-wrapper">
    <div class="container">
      <div class="concept">
        <h1>山の上にある、</br>ゆったりした時間。</h1>
        <p>海渡り荘は、横須賀の海近くの山の上に佇むシェアハウスです。</br>
        ゆったりと流れる時間、鳥のさえずり、波の音。</br>
        ここにいると、不思議と心が安らいでいくような気がします。</br>
        新しい人生を、この丘の上から始めてみませんか。
        </p>
      </div>
      <ul class="links">
        <li><a href="/photo"></span>写真</a></li>
        <li><a href="/price">料金</a></li>
        <li><a href="/access"></span>アクセス</a></li>
        <li><a href="https://twitter.com/Umiwatarisoo"><span class="fab fa-twitter"></span>Twitter</a></li>
        <li class="sns-link"><a href="https://www.youtube.com/channel/UCUaSxee8CCdMknmVM-Hh6ug"><span class="fab fa-youtube"></span>Youtube</a></li>
      </ul>
    </div>
  </div>

  <div class="bottom-wrapper">
    <div class="container">
      <a href="tel:080-6595-6098" class="contact-phone">Tel: 080-1234-5678</a>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/confirm.html.erb
<%= form_for @message, :url => done_path do |f| %>
  <div class="message-container">
    <h2>内容確認</h2>
    <div class="confirm">
      <strong>名前</strong>
      <p class="p-text">
        <%= f.hidden_field :name %>
        <%= @message.name %>
      </p>
    </div>
    <div class="confirm">
      <strong>メールアドレス</strong>
      <p class="p-text">
        <%= f.hidden_field :email %>
        <%= @message.email %>
      </p>
    </div>
    <div class="confirm">
      <strong>内容</strong>
      <p class="p-text">
        <%= f.hidden_field :content %>
        <%= simple_format(@message.content) %>
      </p>
    </div>
      <%= f.submit '送信する', :class => 'confirm-btn' %>
      <%= f.submit '戻る', :class => 'confirm-btn', name: 'back' %>
  </div>
<% end %>

app/views/messages/done.html.erb
<div class="message-container">
  <div class="done-message">
    <h2>メッセージ送信完了</h2>
    <p>
      メッセージをいただきありがとうございました。
    </p>
  </div>
</div>

app/views/messages/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Umiwataru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <div class="header-left">
          <a href="/"><img class="logo" src="Umiwatari4.png" alt="ロゴ"></a>
        </div>
        <div class="header-text">
          <p>山の上のシェアハウス</p>
          <h1>海渡り荘</h1>
        </div>
        <div class="header-list">
          <ul>
            <li>
              <a href="/">ホーム</a>
            </li>
            <li>
              <a href="/access">アクセス</a></li>
            <li>
              <a href="/price">料金</a>
            </li>
            <li>
              <a href="/messages/index">お問い合わせ</a>
            </li>
          </ul>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>